classDiagram

    class Perro {

    }

    class Raza {
        
    }

    class Camada {
        
    }

    class PaternidadProbable {
        
    }

    class HistorialResponsable {
        
    }

    class Persona {
        
    }

    class Concurso {
        
    }

    class TipoConcurso {
        
    }

    class Participacion {

    }

    class TipoReconocimiento {
        
    }

    class Ciudad {
        
    }

    class País {

    }

    class ObservacionSanitaria {

    } 

    class TipoObservacion {

    }

    Perro --> Raza
    Perro --> Camada
    Camada --> Perro
    Perro --> HistorialResponsable
    HistorialResponsable --> Persona
    Concurso --> TipoConcurso
    Concurso --> Ciudad