classDiagram

    class Perro {
        - str nombre
        - Date fechaNacimiento
        - str sexo
        - Raza raza
        - Camada camadaOrigen
        - HistorialResponsable[list] listaHistorialResponsables
        - ObservacionSanitaria[list] listaObservacionesSanitarias
        + getResponsableActual()
        - registrarCambioResponsable(Persona p, Date fechaInicio)
        + getParticipaciones()
        + registrarObservacionSanitaria()
        + tieneRestriccionVigente()
    }

    class Raza {
        - str nombre
        - str descripcion
        - str paisOrigen
        + esDeRaza()
    }

    class Camada {
        - Date fechaNacimiento
        - int cantidadCachorros
        - Perro madre
        - PaternidadProbable[list] listaPaternidades
        + getMadre()
        + getCachorros()
        + getPadresProbables()
        - validarSumaProbabilidades()
    }

    class PaternidadProbable {
        - float probabilidad
        - Perro padreCandidato
        + getProbabilidad()
        + getPadreCandidato()
    }

    class HistorialResponsable {
        - Date fechaInicio
        - Date fechaFin
        - Persona persona
        + esVigente()
        + cerrarVinculacion(Date fechaFin)
    }

    class Persona {
        - str nombre
        - str apellido
        - str dni
        - str telefono
        - str email
        + getPerrosActualesACargo()
    }

    class Concurso {
        - str nombre
        - Date fecha
        - str frecuencia
        - TipoConcurso tipoConcurso
        - Ciudad ciudad
        - Participacion[list] listaParticipaciones
        + registrarParticipacion()
        + getParticipantes()
        + filtrarPorCiudad()
        + filtrarPorPais()
    }

    class TipoConcurso {
        - str nombre
        - str descripcion
    }

    class Participacion {
        - Date fecha
        - Perro perro
        - TipoReconocimiento reconocimiento
    }

    class TipoReconocimiento {
        - str nombre
        - str descripcion
        - int nivel
    }

    class Ciudad {
        - str nombre
        - Pais pais
    }

    class País {
        - str nombre
    }

    class ObservacionSanitaria {
        - Date fecha
        - str descripcion
        - bool implicaRestriccion
        - TipoObservacion tipo
        - Persona realizador
    } 

    class TipoObservacion {
        - str nombre
        - str descripcion
    }

    Perro --> "1" Raza
    Perro --> "0..1" Camada
    Camada --> "1" Perro : madre
    Camada "1" *-- "0..*" PaternidadProbable
    PaternidadProbable --> "1" Perro : padreCandidato
    Perro "1" *-- "1..*" HistorialResponsable
    HistorialResponsable --> "1" Persona
    Concurso --> "1" TipoConcurso
    Concurso --> "1" Ciudad
    Ciudad --> "1" País
    Concurso "1" *-- "0..*" Participacion
    Participacion --> "1" Perro
    Participacion --> "1" TipoReconocimiento
    Perro "1" *-- "0..*" ObservacionSanitaria
    ObservacionSanitaria --> "1" TipoObservacion
    ObservacionSanitaria --> "1" Persona